[global]
enable = [
  "MD001",
  "MD002",
  "MD003",
  "MD018",
  "MD019",
  "MD020",
  "MD021",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD036",
  "MD043",

  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD030",
  "MD032",
  "MD051",

  "MD009",
  "MD010",
  "MD012",
  "MD027",
  "MD028",
  "MD031",
  "MD047",

  "MD026",
  "MD033",
  "MD035",
  "MD037",
  "MD038",
  "MD039",
  "MD044",
  "MD049",
  "MD050",

  "MD040",
  "MD048",

  "MD011",
  "MD034",
]
disable = ["MD013", "MD014", "MD029", "MD031", "MD041", "MD046"]

[MD002]
level = 2

[MD004]
style = "dash"

[MD029]
style = "ordered"

[MD013]
line-length = 80
code-blocks = false
tables = false
reflow = false

[MD026]
punctuation = ".,;:"

[MD033]
allowed-elements = [
  "i",
  "q",
  "cite",
  "a",
  "time",
  "sub",
  "figure", "figcaption",
  "iframe",
  "table",
  "summary", "details",
  "math", "mo", "mn", "mi", "semantics", "annotation",
]

[MD049]
style = "underscore"

[MD050]
style = "asterisk"
