[global]
disable = ["MD013", "MD014", "MD029", "MD031", "MD041", "MD046"]

[MD002]
level = 2

[MD004]
style = "dash"

[MD029]
style = "ordered"

[MD013]
line-length = 80
code-blocks = false
tables = false
reflow = false

[MD026]
punctuation = ".,;:"

[MD033]
allowed-elements = [
  "i",
  "q",
  "cite",
  "a",
  "time",
  "sub",
  "figure", "figcaption",
  "iframe",
  "table",
  "summary", "details",
  "math", "mo", "mn", "mi", "semantics", "annotation",
]

[MD049]
style = "underscore"

[MD050]
style = "asterisk"
