[global]
enable = [
  "MD001",
  "MD002",
  "MD003",
  "MD018",
  "MD019",
  "MD020",
  "MD021",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD036",
  "MD043",

  "MD004",
  "MD005",
  "MD006",
  "MD007",
  "MD030",
  "MD032",
  "MD051",

  "MD009",
  "MD010",
  "MD012",
]
disable = ["MD029", "MD041"]

[MD002]
level = 2

[MD004]
style = "dash"

[MD029]
style = "ordered"
