base_url = "https://mnt.io"
compile_sass = false

taxonomies = [
  { name = "keywords", feed = true, render = true },
]

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
bottom_footnotes = true

[extra]
