base_url = "https://mnt.io"
compile_sass = false

taxonomies = [
  { name = "keywords", feed = true, render = true },
]

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
bottom_footnotes = true
external_links_target_blank = true
lazy_async_image = true
insert_anchor_links = "right"

[markdown.highlighting]
error_on_missing_language = true
# Use an empty theme, because giving one is required. However, a custom CSS
# stylesheet is used to highlight the code. Only parsing and adding CSS classes
# are required, not adding colours to it: it's the role of CSS.
theme = "noop"
extra_themes = ['code-theme.json']
style = "class"
